#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Fri May  3 15:07:53 CST 2019
#define HttpTools NVFAGDysNqvhBdtL
#define httpConnect xhjZtwzpADLjEpaN
#define url bRmgIoaJIeZOCKkE
#define type meEugHkEJUwCagcG
#define headers EsEurQWtxaMGvWkB
#define uploadDic HgDhgFvbyQIuhUKn
#define callback xASZtgMlBYNLJwOd
#define resultStatus fGlvXXgKQkxXttXD
#define resultHeaders xIcpLJdcPMdvVWGP
#define resutlData rAgwpUJtKFqiCbtM
#define resultError KLdXqtpMNPALqiTI
#define request XXPjSljIBXqRaFrn
#define session tAlbjxAVChTqzRcA
#define task pfeAHrOtJaFSLxWY
#define data NILONkFsvlAnxfZh
#define response MlakWMxJNjioJLjj
#define error BSfutmMCWDiDcHHJ
#define httpResponse jCtTKwtcfUMJccsq
#define headerKey feRxRnzcDBaENYsW
#define headerValue hFatysiOFmyVjBDh
#define downloadJasonDataAsDictionary RAnOzlBaoPThAYLg
#define resultDic bIkAysXwMatJXaRF
#define errorString RNgsMzeCxbLZkANd
#define downloadJasonDataAsArray MhVtmZkTtHWJVJkY
#define resultArray nKRlyHJzbnshUGBL
#define downloadImage TOwamhsJFwuElqHK
#define ClosureWrapper kScaTFWTTesnGSlw
#define SplitViewController xbFFCgkJwiIcZmtz
#define totalPageArray RraGbCQEavDbqQzy
#define totalCateArray GAQYIIChIUiXXFIO
#define counter hvqaWIIsDKHIVGrf
#define naviVC jDzlVduBiBdrqUyX
#define rootVC flHZOyZjnJLpKAqh
#define detailNavi WrlYMXdHxAIwjeOu
#define detailVC PfvyvakJxmkzfQhm
#define userInfo nrWnxIqQRuyVBruE
#define naviVCTemp IERxnuUgJyVnHvmZ
#define rootVCTemp BkYSBtAxUJxlempJ
#define detailNaviTemp WBUxnkdTUjYqRCqM
#define detailVCTemp szcMNvYnqEtHFWFA
#define vc pTBkOVseZOoDpsWV
#define lang QhpqCqvxoOnXYHMN
#define isRecommend DFGpYuujTkCAyVlE
#define resetData mRcpULopwoTbIQaR
#define totalPageArrayTemp VJNKblhVcFRfTPsI
#define totalCateArrayTemp ltGCOEMPbDtNjCil
#define newPageArray FagMywMBPkWGQjVL
#define dataDic RKsgQJZqdDUcPuxe
#define cateName TmfixSZzwlAQmkPn
#define cateNameTemp rLNfiTjoahVNfTOS
#define dataArray zTKwuKlXtirRwmsl
#define contentDic HDMsORYSHDABNeAO
#define pageContentObj BIubdoTqzfJTYbEp
#define titleName TIYgpTUqOEkNbkhv
#define subName bQCANTYerYjCAWho
#define id nGXeSOdFPNTvpFij
#define editTime MnvVkjVQFHojcGnm
#define imageUrl LLcHbXiZFtRkXsCN
#define tagString BueDDzAEmGUwMjWv
#define tagArray mXptsDckPkIwurkN
#define attentionArray IPDCbExxvBVzRDNh
#define indexTemp IvbMVCTGLoSOGIwO
#define attentionObj glcXiGRkzpsfcySg
#define index mwrMHfzHqggEDGus
#define resetRootViewData KbvCGWBSYagvBBPz
#define resetDetailViewData DERQbEfKiDOOoYRt
#define checkLogin JEdxmFnuyMXcfgrG
#define loginVC sbcsIvObuOAxfaLc
#define registerVC FSgcRQnssjLrVLUR
#define showRecommend xjjIDbGFdtqdKfjB
#define maintenanceUrl cnEciPWoUOXcdJoJ
#define foodArray dJYUFohFrRhwrtEt
#define overWebVC avOhkcxnrcMyARQc
#define foodDic VjSVzRAcGeBGSDlj
#define titleNameTemp YVKXJPwEuRSAoyul
#define contentUrl CZsCqBxuGWAZyQtB
#define contentUrlTemp IdETXEblXpUtovXG
#define accObj ePJexhKLrsOpfbit
#define RootViewController gwNlTAoQdtWSqbhB
#define rootTV PgnZNBobDBwWJSMj
#define RootTableView tlyKzxTxgPtwbaEN
#define rtInstance lgELZNhMkRqOGSAo
#define rootViewDataArray MzDuSgdultsiABFh
#define cell cbEXXCZefipRFIWu
#define spVC qgTOMOqWgLMAmROY
#define iconImageView tYKMAFvsoSxYtJbs
#define iconImageWidth hTnpnFSYtBdjmKXG
#define nameLabel lgOEwsRIXCpiyzCK
#define NavigationController RrsPWKUuaROiuDHZ
#define DetailNavigationController oZSJFwdjqfShmhIH
#define ViewController aTXVxqBASLAPtJQP
#define viewControllerTV TwdqlYiwvcdpDCeL
#define noneLabel aARIBaJCHOPGDkJQ
#define searchController CAYqxTwYIEYBhltt
#define homeName uDqSPBLNDLdcndBs
#define attentionName CHOQveztOwPYXUhs
#define postName KFYMtPLvMALdXeFp
#define commentName TIaqSMpdfXOzrbME
#define userInfoName WrpwgstWucElQTJq
#define noneAttentionName qBycAjGwaYejtUgq
#define searchPlaceholderName iehHQwLlAuGmLyhg
#define searchBarBgColor nlqiAtckJkqkjnUL
#define searchBarTextColor IJTTKIRzkqcTUXKe
#define searchBarButtonColor pvvGbPWakwLRyumU
#define selectCateName DswxUEoSvRtqLkhB
#define toolbarSelectIndex iSJpupXvxHxebTLa
#define featuresName RhFOUgwrzSOSBVSF
#define toolbarHeight ODQLsfdGOkPuSAjO
#define toobarWidth xBjngjZgjiOPhsbj
#define toolItems wgjdnyedTQXnDaHO
#define homeBtn tMJLKIwIhytXRDAD
#define attentionBtn QXmzryPLTEqJTnnW
#define postBtn YjUCOpHMGmxYecPn
#define commentBtn rwwwwCxRKrGFpWAp
#define userInfoBtn lwkYsWfUsbIqTDWx
#define showAttention lsFGtkSruhunYQNw
#define showPost QjdURCQrztDoHTef
#define storyBoard uhOywVRfRrOsqyNa
#define nextVC esxAyblwGIUPlgfx
#define showComment QIUyxxsylwIUKpks
#define discussVC anpCHsMnZwyWIcKJ
#define discussObj upoxGsxjbVrZSWGS
#define repostVC HhZzozWWeqWmTtel
#define showUserInfo fDaQgnqEFcOCcPjD
#define updateCateSelect BrNBXZUBHPLQzXUe
#define spVC pEGoGcemoaCIQJey
#define rootVC ypqqOShzpoENrFGA
#define updateSearchResults OmrFTbGjEmWMgXjl
#define isContains iEbqMJWfJclPdJFv
#define ViewControllerTableView rYEGoDLtvLPjtltO
#define vcInstance hhlnIFsGgwcFprBk
#define allDataList mVDXdGjgCTLQIYKy
#define cateDataList EInqJiIfGcntCHbH
#define showDataList pKAtGjKwWYeyVaek
#define attIndexTemp KGVAVpZqyYilaQCq
#define attIndex ijgizJJGIHhLElCi
#define cateIndex uboqPmIfJQWwPsCT
#define ViewControllerTableViewCell QGnJnCPTdDYvtJSW
#define cellMainView rwMNkCnTlZRCpyZb
#define cateImageView kYAPdhNgCoLitQhb
#define cateTitleNameLabel KAAHLAYvjZCSOIJd
#define cateSubTitleNameLabel HRJooSQzQbEutfFi
#define cateSelectBtn vhbLVCQCGgASlrcx
#define cateAttentionBtn bcjxcVJZPCOdfRdz
#define cateDetailBtn cuLNVlebpDtovcGK
#define mainColor EfkjJGcJZnZPvcUH
#define subColor jWmivvjzaMsCszuI
#define PostViewController LtvhkYUnBgVixJAd
#define cateArrowImage LLGtlsQWgDmyzTyu
#define cateView FnRQbOcLyUhgmYcy
#define cateLabel XBvGsAeuDLKakUCS
#define mainLabel MsHzsfLHcKIkGtLf
#define subLabel VKeMGMFpSiObilvW
#define urlLabel mTvfXNhRBhmnIhSb
#define tagTitleLabel vnxnUgDkTJVRrnHg
#define imageLabel amgKsivmwmjKpMIC
#define spinner QMgNhMXYetPvXuoI
#define mainTextField sqsUizSOoNZVPtXz
#define subTextField jUIdNVyseeKmbSyG
#define urlTextField ecgjuAWruyOjbFOp
#define tagLabel JkNoPPoHhXeAawXq
#define tagAddBtn vfJJkfYIBqHZHlib
#define postImageIndicator PADqucVAzDSQNwud
#define postImageView cgcIFJBUHArULTFH
#define postImageViewHeight tuxugdGWTmeTncPD
#define postImageBtn hcjPXitFClAoAyRJ
#define sendIndicatorView kKedZGgifsRVKFQu
#define sendIndicator ZXHflAkYTMlHPByj
#define nextMenuId GUcxzZeigqohVOFb
#define imagePicker AeemGxylBPSkkgtg
#define imageLink hXbBHcYjFvkZGckv
#define controller mwxWRDdpOikDPUKU
#define textField imWhvVOLCHxLQFvc
#define okAction kiYgxYBOiksfTPaH
#define cancelAction GbhGOTFQtJeTUJTg
#define toolItems uAxDqsobbddAKMlO
#define cancelBtn DMxyYPqRTlcwsNTo
#define sendBtn QtBahHCMZAUkcdKm
#define newPageObj mdKnNlnrLAoscQbZ
#define df jomdElOvgmZwAuAn
#define requestPhotoAuth raRXmSCkVQkDiqeh
#define photoAuthorizationStatus jQJiLquXlIAjTWlv
#define authorizationStatus xiGPzObjZIgSBYnM
#define alertController PNPvjySQsdbLPGYl
#define pickedImage jIYiEPcAarmdptIV
#define SimpleSpinner ePaAEbPmXsOLWqIl
#define isEnable KRdUQtAdulXataeV
#define insideOfView zscGKsvcUoEymNWg
#define spinnerDefaultItemPosition EwZnVbOekzwMNALq
#define spinnerLeftPadding UQhGwLUKHqBrjmSF
#define spinnerRightPadding YqlJThGjeYyZpncF
#define leftGapView yLfzatwdIGNocEQU
#define rightGapView seuGFZJduOQNUjEH
#define spinnerTextFont FHotmqgIbfotdPGa
#define spinnerTextColor EmFMHzSFYvdWDwHa
#define spinnerTextAlignment whqpKhnFzNbAAbbN
#define spinnerDropTextColor GXVyeldMToEQBPst
#define spinnerDropBackgroundColor hIdgTSvFgZwNgtgf
#define spinnerDropTextAlignment CEXHwGOJMInxAKhO
#define spinnerItemPaddingTop fGFkluglACWyCeQd
#define spinnerItemPaddingBottom PWQwAlpeRGXIcGBA
#define spinnerScrollView wFaAAXKnpkJPVfxW
#define spinnerCancelBtn XZOikXGbrTUtWyZg
#define spinnerSourceView pDPJXvAawLYoiFax
#define spinnerLabel soJXjObDbLWUMzPb
#define spinnerTitleStringArray WdWblCtUscvYJAIZ
#define spinnerCallback czidotQmFfvuyOex
#define createSpinner NOKYloSBZHtXuxtE
#define insideOfView HCCzOFksEQpBUKUZ
#define topCons izpQlOfDmROODCyY
#define bottomCons aqaNWDfViZCDyOOP
#define leadCons NimSIDjamlyPZMQq
#define trailCons IgSrxaGliPFfPosy
#define topConsLeftGap mZMkCXYmcMgMauVJ
#define bottomConsLeftGap iLLejeJeaaRevxhl
#define leadConsLeftGap hlrkdQademnaojZP
#define widthConsLeftGap DgnMZtFkdfYPyTsG
#define topConsRightGap PcCiEeRLImvYWIrV
#define bottomConsRightGap JtraDwuaYbxebeaT
#define trailConsRightGap SlCdhvUvhwxnjxxO
#define widthConsRightGap FFndJCMEJVjcoMzg
#define heightConsLabel ZsgvRzaIVLbhIYUu
#define widthConsLabel mNGdBKvpdHgOOjXp
#define centerYConsLabel PYyhQYlxhCycSRfe
#define leadConsLabel cABJwEMGhlcdcRuX
#define trailConsLabel EhbmqUvFNJNxWFPv
#define heightConsLabelView TDWZYiqgqyNUxLsP
#define spinnerBtn TpMsOGhCZgGURbzP
#define topConsBtn UQJzXeCjeuQFgdCn
#define bottomConsBtn lsIwstTlWDvAFHDW
#define leadConsBtn SOxJsbiyKibmCAQL
#define trailConsBtn DteKpgpSDJEjJWOt
#define removeSpinner iEzqAOYgjIxigRzw
#define spinnerScrollViewDisplay xxQrHwupeKhShDnX
#define absFrame xdXYETareXhyVUVb
#define outermostView kZDHkHcNBLzbactU
#define upSpace tnZWTPqrmoovvxzQ
#define downSpace xsmafpbBzWWAvvmV
#define useUp HOdpkddDrmzvqJHB
#define maxWidth VwdOpvbPzAgOkJwd
#define maxHeight dmZmCHbBlQlzuZnp
#define cSize CMVjTLQIURCmaFfd
#define cWidth wyjhkucEDsRygpkt
#define cHeight fGwaWlhdHapztXzg
#define displayItemCount QGvirlZCeNfBrWGp
#define topConsCancel PTuEhuYUaKVzdAZj
#define bottomConsCancel hTKRmGZldrvfzbgm
#define leadConsCancel LVgsVlUWjTnmPZHl
#define trailConsCancel rqstWJivWOAdkFNk
#define scrollContentView plngBAXTcFKhobZq
#define topCons oZaPldezcjtVaUuS
#define centerCons nAlVboHbiWUfiwPk
#define widthCons OMSTwYIXjQbuCkIA
#define heightCons iOfdVpbNypFBMsxy
#define itemBtn pWOwLAWVLrQrJyUG
#define btnHeightCons JRtvAPdhVzKPYdUA
#define btnLeftCons YMvEmwqVOydfAOgA
#define btnRightCons lnYkfNkaAzMCCeMF
#define btnTopCons TpXgNXvAuhxhLapH
#define currentItemBtn jLlYcbPhDTOqLVAA
#define itemBtn2 JWWwgiAPZJnAUbPY
#define btnHeightCons2 TAXgAtkRNlZUMssg
#define btnLeftCons2 spmnGjwpiwuegiTw
#define btnRightCons2 xEiNRWknEYFrYCqW
#define btnTopCons2 DusBXxXJjcPIafVP
#define btnBottomCons PYLpPWzALgWHzkTd
#define spinnerScrollViewCancel mXKZCoCFvVCKmwSw
#define spinnerScrollBtnClick ZxcDnmLiavIlpgAn
#define setSelection oilZyBzZnhLaLHDV
#define getAbsoluteFame DEgfcvhQiNduTvsU
#define originX sGzdkEFgkGahfFrF
#define originY PVjxZGFOHhMqWQdz
#define superView HAtNlYvyMLXuOOEv
#define getOutermostView DcHlgNBmlkKPtcrs
#define UserInfoViewController ZMJBIMMePOlGWjjT
#define userInfoTV GcucgQMepUzgKRcN
#define UserInfoTableView plORgDxKuDovOgTq
#define vcInstance gUcsJVdUmQsDEiEQ
#define imagePicker bkpytstOgXEnyLsv
#define UserInfoTableViewCell YUDBXpvJPundVDAn
#define userImageView vWwdRNlsYunmGTdx
#define userImageIndicator KSHpHIaIYsWtiQya
#define userImageSelectBtn RvpiGSbgRYxVlCrc
#define userNicknameTitleLabel FKAmLvAjQiRYWefZ
#define userNicknameLabel QJElRxBmmvbkgodN
#define userNicknameBtn yynIphPbWkIBxXpR
#define userNicknameTextField bvAAEbrnCfjBrFez
#define userEmailTitleLabel ebViNHLQeyxvPeCo
#define userEmailLabel qBUCncDDRmMeOMkf
#define userEmailBtn cjXbpBBQmnUuBecN
#define userEmailTextField dxkRqzDQRoUdLXVq
#define SystemConfig ZjMcioScaKkbqgGo
#define appCateId hbnCYFRkPAPqOJbA
#define appMainColor TQeDfcGcKphsbKUv
#define appSubColor nkTLupFQPMHGQzJC
#define appSubTransColor ywVGBhzYNKLHjMHX
#define appMaskColor SAXOhbwjrwibProP
#define appLightColor BYkavRjXqbJqntLX
#define mTitleFont YLchyFQRsdNPnbbb
#define jpushAppKey wzgSwzRYPgCEJmHa
#define jpushChannel LSTqpgvlZLumVwyO
#define leanCloudAppId FEDhGUYikuNsbVBi
#define leanCloudAppKey FiaLwiNmYMASvGwu
#define sendBirdAppKey hkRYYjIRTZlvRKha
#define appSendBirdAccountChannelUrl nhmougoujrqJVIvP
#define appSendBirdNewPageChannelUrl BUBYBFafbBYwClka
#define appSendBirdDiscussChannelUrl DfSItVugwshBwcot
#define appSendBirdRepostChannelUrl uvFYltOCDYpnXvMh
#define appSendBirdLikeChannelUrl GZZGVAzFzuxaBEzI
#define RepostDiscussViewController GmSdspIzElwLcXiX
#define backgroundView DZbqTEWoSafxNSBj
#define backgroundImageView aeWBJhtahqhHLqzy
#define repostTV ZneVorGjKwkMbdwX
#define sendView eyMDNGoPapPVgbHi
#define sendTextField aAtdVDAfjHPtMzcX
#define sendBtn YlaIlVqoeWCraXkZ
#define sendBirdDiscussChannelUrl NhGCmodcHzvGjxio
#define sendBirdRepostChannelUrl bMLDvfZRFqPyvaej
#define discussId sjZhWokOSuUnSXMb
#define discussObject qYQWboCwIqlJZioi
#define resetData RbtmUwzcKttiGGPk
#define discussObjectTemp mmuDHiHSKaPsJUrK
#define repostObj TGxUUXwJxqlDKapM
#define setParameter ZkCKNGEIiSToGdKU
#define sendBirdDiscussChannelUrl FwCOfpyAsRyDgDmf
#define sendBirdRepostChannelUrl gJzRAEKxUOkHSKtq
#define discussId tsFOgdmxtCDNjVyC
#define userInfo rfJlVQxUQluYmGTy
#define RepostDiscussTableViewCellM ZXzpNweQptjReiuc
#define cellBackgroundView fPeLptpItxEarQaV
#define senderImageView YsnMlCGhuLXnYPMv
#define senderNicknameLabel dYkMrcBSWXqPSmgp
#define accordingImageView BpvKBDjlsGHgShdw
#define accordingTitleLabel ZYdEawtipvZctIVt
#define accordingSubTitleLabel lXroQhMAEFxGWCii
#define subjectLabel rwORUqVBPfTojZlk
#define contentLabel kANdjlTYochtcviY
#define RepostDiscussTableViewCellS ktlJaFGSrdmnCNqe
#define cellBackgroundView LoSciUgXfVTUpwNG
#define senderImageView TzIufKWDoSKMgedU
#define senderNicknameLabel mcIVLhHpQghzSmff
#define contentLabel ECiZQIfbrkEEsZaJ
#define dateLabel WksfsNYyKcuwdKOp
#define QueryDiscussViewController fPVpTCvxbLubULUj
#define backgroundView eEDKsxOLofTTqWoG
#define backgroundImageView kAYcFpNuVSwBptHJ
#define discussTV ddTAloOCfkrKshgo
#define sendBirdDiscussChannelUrl pfftcvewMZeTZUnT
#define sendBirdRepostChannelUrl GTaJTWkziTARFtzK
#define sendBirdLikeChannelUrl opaDXdEAgmgxXYME
#define userInfo TfiheANYxtoflJHX
#define discussArray lXOvWZIVGcBgFNXB
#define accordingClickCallback CqOpDpNacKTgOHQd
#define repostClickCallback JSHZKgSnjYhWszyq
#define sendBirdDiscussChannelUrl vrTicwdZItLjiEEB
#define sendBirdRepostChannelUrl cVkPAUDegppOTQVz
#define sendBirdLikeChannelUrl QPGuHlbIFikieoAV
#define accordingCallback auDiNbwbjiQLZhaQ
#define cellBackgroundView sknuVnTHYHWYJImQ
#define senderImageView svmjBeDWMVYNhJWi
#define senderNicknameLabel krBhqLIgeIIclmPe
#define accordingImageView MwjTwYTNlUYMillE
#define accordingTitleLabel bJYmJYukWlkedRmH
#define accordingSubTitleLabel oGysIOBqVwPEzgzU
#define accordingSelectBtn cNCZtISMxSqvczVv
#define subjectLabel TIhCWxjcWCkHIzsW
#define contentLabel xoQmOlRsDBslcwbl
#define dateLabel bSpKMvahgtFXUSgt
#define repostBtn oDNBoPiXywfOSCiu
#define likeBtn nKnfLpvtZWDBEtLz
#define backgroundView oZutWpPpAEOocMXO
#define backgroundImageView UafqsdPJVhCuAAAu
#define sendDiscussView vdYoHDLgrHAYATur
#define topBarView qvpLbNJZzvoIQFFq
#define topBarTitleLabel vqtTJmFoTADoJFBz
#define subjectTitleLabel eAEBADfONbvurjGR
#define contentTitleLabel sXrejdLSbLtcTWUw
#define subjectStrokeView lnriABuoZqciptzc
#define subjectTextField LuhXwqqjkVjCnhrh
#define contentStrokeView AOVxLzKXYMBzXjce
#define contentTextField gIhpUhcbfiFnPMVw
#define cancelBtn slfSvJjiicyeXsKe
#define sendBtn UjMiOfReBmrgBCAz
#define sendBirdDiscussChannelUrl zwdZvJZFmphANkrh
#define accordingObject pzkXpbTnREYuKaBU
#define sendClickCallback uioXEbNAHYlivhqc
#define cancelClickCallback NUXGegKNIwKDKjZH
#define sendBirdDiscussChannelUrl PNoNwGfBybppNVMw
#define accordingObj CCfXFexpRqCJInfz
#define didSendCallback XXcmmExuFADXRzll
#define discussObj FpmrTZurXwpJvUuk
#define cancelCallback ehFeHufNDSiWpSPB
#define LoginViewController LawdfTusSjWhOjcz
#define backgroundView URPijJLWCXUamsJj
#define backgroundImageView QAxTDROsJRxxmsdT
#define loginView koJuoOesTtojntaV
#define topBarView qvRrHGxZXkKBOdqe
#define topBarTitleLabel omhzNptCOHUwWBkx
#define accountTitleLabel tFwItohHbccEQNIF
#define passwordTitleLabel yQSPOcdGquwWgKGJ
#define accountStrokeView wpYGXuEgJonhJGBj
#define accountTextField KeKKZncTTfyBtHgp
#define passwordStrokeView eMmSTXxFnxIczYQb
#define passwordTextField VVSKLKQPnDbokmxM
#define cancelBtn bUbpcJgYLiURKMpf
#define confirmBtn bTUviSJztsSHDGzI
#define sendBirdAccountChannelUrl OswoJIkHmyaQnlwZ
#define RegisterViewController NbveloiTngJVMquO
#define backgroundView hxRAfqAFQUmfOMMU
#define backgroundImageView SSmVczdyOjnKASmz
#define registerView qnqUIDmdtlvEoKmO
#define topBarView JECSFYvwxxVlYTTS
#define topBarTitleLabel SGaLWMRqCQkJYZej
#define userImageView rtyaXcbCSgPffTHx
#define userImageBtn JUtUcNcUyCXtldXl
#define nicknameTitleLabel BfJkTSBJexnWvqVV
#define emailTitleLabel bTpwvRkMrOboVYZH
#define passwordTitleLabel qruKHZhlEDhfaSqQ
#define confirmTitleLabel MfTVededtheQNZJT
#define nicknameStrokeView QLmqmPgFQshAkscf
#define nicknameTextField WOJvJFtcNRvViWom
#define emailStrokeView xVIXjHocrhwqCgWB
#define emailTextField eFgmGreRjbqfSCUk
#define passwordStrokeView gxJHEhxpizeAqCxd
#define passwordTextField rSbbuJtvHUdcJxIR
#define confirmStrokeView qUgThlOTmlTQKIZl
#define confirmTextField bCSAylqPoVzCzgKd
#define cancelBtn vuoOAsjZlvzeWmPn
#define submitBtn GEVoqdnTwzCbimlc
#define submitClickCallback SvKFRxMsdpFnPnDd
#define cancelClickCallback SOhxhllmJALiWLBn
#define imagePicker BGVssQkgHaQWGggE
#define sendBirdLoginChannelUrl bjCmlZnFRfWiAVdn
#define userImageUrl EBCtukFNnFWdxMDL
#define sendBirdLoginChannelUrl EJSCrjqLcobEdbDE
#define sendBirdAccountChannelUrl xBhfoAqjKTrthHsf
#define confirmClickCallback HDDuoCXMYvSsmokM
#define cancelClickCallback XUOgmJduBWQDzLRC
#define didRegistedCallback PhUREBUKjTbCVKyt
#define OverWebViewController JSicTAPRXHFDBjaC
#define titleView hPpxkNmCeubwSFyi
#define titleLabel kFLMInTnmpAHebUi
#define toolsView ZdqhicXygrATQAIo
#define backBtn CXfPBrdXNuFWnTaA
#define forwardBtn NgrhAKngQTwhWpBR
#define refreshBtn mbIQQyKLeOyhciFJ
#define shareBtn BIsXotHcJKlsNnJa
#define wkWebView pTulhpDMkxlDQWMw
#define exitName WTwXVfsbaYDxtmqt
#define backName cJppZbdbnITnkFGr
#define forwardName znZHZhILLZMYFWig
#define refreshName vhSHPVnSOcMuMXHL
#define shareName TVpGFGaBCoxzQErp
#define titleBarColor bjMQaFwoCMpcXDmD
#define titleTextColor ktDjSaCnnVCdtkdx
#define titleTextSize cMcqlmLGTLJztisv
#define toolsBarColor tkhTWSJVRrskxnvT
#define toolsBtnColor LXpsKbeKJrOmEeKH
#define toolsBtnTextEnableColor KxDaUePyaIrMajpb
#define toolsBtnTextDisableColor PriNhkFTjGQBCLiW
#define toolsBtnTextSize UemxlRYWBqqlNxAX
#define cancelClickCallback FcfPfRhFGKVsMnja
#define accordingArray djSKjZvgUzxHdZSA
#define isInnerArray xycmtmKEaIDRKkZE
#define currentUrlIndex XPeDnGDTEoQzwpXM
#define mainView mccbNdjzjbusIkgt
#define leftView ICRddODxYKAMbFJL
#define rightView bKJVgsDiSOPvwpcZ
#define topView yxsBRSpjiroLaDIj
#define bottmView vdloCVggQrHtrmWl
#define gotoUrl FltZfLPlWWnLkvYl
#define resetBtnColor CENXbFyxWLuKsTnV
#define loadTitleUrl pwIMkIQajYgZBBuo
#define setCancelCallback btseGpMrCktzPlBv
#define backBtnClick fKgRQSMcSXClFmjF
#define forwardBtnClick zjLixfljQHZqqSZf
#define refreshBtnClick WNqLSmbaPFVoJrQT
#define shareBtnClick UCmrgEBIDfVMCXZx
#define addMessageBtn WpYHOovlvFCRsScm
#define messageBtn bdoDDeccgYtEerlm
#define sendDiscussVC UtiNkOlkzuxfYsvH
#define KeyboardControlExtension HGtiHmedqqoTzJVn
#define kvcIsKeyboardShow SDbwVueGwENicAjN
#define kvcKeyboardHeight tUMHkmPnwVTaKDnN
#define kvcMainViewFrame LVUTAvwqqcHiRPxQ
#define kvcTargetView mbxLfhdOykcfvbMO
#define KeyboardViewController dJTtzAdNuOLlVRhA
#define mainDisplacement UPXThdFvbAudlmOh
#define bottomInputViewFrame ZKNLeyGGemhvNhNj
#define bottomSpace UVJAzxXnzfJAqbWp
#define bottomInputViewFrame FrPJMONxqeSTmsPf
#define bottomSpace rVxSmowlBSHdwcvJ
#define kvcGetViewOfAbsoluteFame DixaScKWrQBlCzNm
#define SendBirdNavigationController dhZtjnoYjzsuqahD
#define mTitleAttributes fvvcWSieGqiCuate
#define UserInfoObject KFXpyBUjmmnwACvE
#define userPassword YkTajPAGwpPpxbjZ
#define userNickname rgBLdkctmkdWvUQZ
#define userEmail gYGWGHCvcnGIsHqL
#define userImageUrl WrXICTFpPfLMBJOa
#define AttentionObject IoMhNOLcLJTZtmhe
#define accordingUrlArray LNICcVTWWIDhPtes
#define NewPageObject ABRYhBqFamHVpbuw
#define menuId CPrBeYuSTOXvCpMK
#define cateName cHQAXaCycaCyqVgY
#define titleName ypkypicpJryojlPC
#define subTitleName BGOMuxhdVJtRswxc
#define tagName aXRuzzbPfJCQAtUV
#define pageUrl xmewgwVYgDbuprPA
#define imageUrl WziQdbcdLrdQdMAK
#define editTime oMcJkiUcXvfAtRYT
#define isAttention XPRXRAsGZawxTbrg
#define DiscussObject dvfqLZhMookrtthZ
#define according RNvHJPkRymURuYHf
#define discussId gUmENCBPUDobyOuG
#define subject WUQRyGEKSnkqaBRp
#define content uvzkLxSCkqtOlnhL
#define date wnhRCDxYSwveBVLk
#define repostArray WiaOXgPfCNUwhOAU
#define like BTDPFuTfpiYNwCGr
#define DiscussAccordingObject ctZfJNoQfZKhEIkl
#define accordingUrl ZLTClgEJYRDBXDxf
#define accordingImageUrl tClOXbzZiaPhxSnv
#define accordingTitle NIrWHwvmaDQveApV
#define accordingSubTitle jstQNvMwumyfMAfj
#define DiscussRepostObject tYhiztGzeLZSoMbw
#define discussId KDanUeLhponSbxyx
#define DiscussLikeObject PQWDGxjFwBkgDwuJ
#define userInfoArray XKwurwRoVSlBKOyU
#define discussId gbSurNGUlhCKXTsd
#define sendBirdInit rOVkhziVUjcrqoHV
#define sendBirdAppId iNyfVMZlYoBFvkEY
#define sendMessageTo uWOkScZOoxjDCUVX
#define sendBirdChannelUrl rcyXZscIacrIjgJR
#define userId OcAQxeAzgtXoOxnE
#define messageDic eLhhWCKyyyhfRWAt
#define didSendCallback YVEnnUElWUOZNaCN
#define getMessagesFrom JUwqPCFIVwDkpUtz
#define sendBirdChannelUrl ZucxWSYtnKcubhUb
#define numbersOfRange dWVKPJsPplQfVzrC
#define messageArray QtKGrHyCOPsrIAPV
#define pageOfNumbers ShdpLOisHUqeUVBV
#define listQuery XHshmQCJXQJeAfEZ
#define getMessagesListQueryLoop PAygliyXDzekWMXF
#define responseArray RMXbJpnbAiKndUQb
#define userMsg laXEpZqVPrnszTVP
#define msg KlAQdPNgbTiWGIzf
#define msgData LoGZYdIBaCSwhJIM
#define getSendBirdUserInfo BrLmbbxyzOiPJWVJ
#define setSendBirdUserInfo NLVcceogPvjdKDSL
#define sendAccountTo btQtVZqctipgtIvh
#define sendBirdAccountChannelUrl pcjiweMvrXhWHYhq
#define getAccountsFrom mSuaoDnrMcrSfYBT
#define sendDiscussTo jEueIdhDBOiFWotE
#define sendBirdDiscussChannelUrl VspDJPoiMXRhjTdY
#define discussObject BJJeQebakPXMfxlY
#define didSendCallback cyiqWvlstklZkRIK
#define getDiscussesFrom gRBZMziEocsPhHvN
#define discussArray xIHEeEWhZtXmEvwS
#define sendNewPageTo efWBfwlTYHwXwOKU
#define sendBirdNewPageChannelUrl yYoCfcflbqLSpuUe
#define newPageObject BfiCGzUiHBmfGAtn
#define getNewPagesFrom gIeXtNCNNoUaBJMw
#define newPageArray JbMlvgjWbNgmQVYL
#define prevMessageListQuery SogeFlZSpPefcsYP
#define sendUserAttentionTo kazrelsoZOvWYatb
#define sendBirdAttentionChannelUrl AKAsgalwUtalfJNE
#define attentionObject WAgyKxQrvDrJwhuW
#define getUserAttentionsFrom hpjtNwhDekgngbDW
#define attentionArray jUNOrZZQukWOZTgb
#define sendRepostTo hmbOHTzPZyuHKopn
#define sendBirdRepostChannelUrl NWJPyMufyNizgbzX
#define repostObject IUeKOsqpodxXpZXl
#define getRepostsFrom uXoZOSvQcdIlYrHB
#define repostArray GKiJDYYqJBcxXKfA
#define sendLikeTo NrdamJiBKijTXPZK
#define sendBirdLikeChannelUrl AjmpsMAdgObeZLPK
#define likeObject vKVrTQWiRmpxJNDx
#define getLikesFrom yuQxHdsYBUKbakry
#define likeArray XCqWCFOgwNTiyZHF
#define getOutermostView ghpJsJXtcNOaaafR
#define getViewOfAbsoluteFame nsmqJqAOZVxUjfFc
#define startIndicator mAravdakhmurTdTe
#define currentVC WHLqIhdvSuXpUkde
#define onView ALIAsQUSZcHsImfw
#define stopIndicator XVyDGuofcrXqyURj
#define indicatorView wDEUagdUdDqVoUwT
#define matchPattern iafyGIeQeLSFxFIl
#define regex WWZzXjnxGPPcIhNj
#define resizeImageLimited qvPNLDJEMIcpIoCG
#define backToViewController IMUVzsGhfCAhAhvj
#define backToVC gihBveynaeyhyLmr
#define getDeviceTokenFromUserDefaults lFNolJQQRXuvcUoJ
#define saveDeviceTokenToUserDefaults nxQwNMoWQaRkeByE
#define deviceToken zDrNqrBTIxbDiluO
#define getCoreDataContext kSOSEvzQbUzkgmxM
#define entityName uxBfxXOuFkeVSHFn
#define persistentContainer FhUFNFFQxwmjDpzA
#define coreDataExample wBGJpRZxFkGKFdGT
#define uploadImageGetLink hsdVIJeZmBBbsUSS
#define urlString pIugRnJGpPWCqfaP
#define authorization DmwDxLIJNmAOiGER
#define mashapeKey QkpZBuPZAhkIJgjL
#define resizeImage idFbtnzuoBuIUhBw
#define imageData ymUIQrrSWoQXyeeY
#define imageBase64 VHmfArkWbszlQtPA
#define parameters QZfdIURLMEvRhfuW
#define getDownArrow lvYmMCcYZCKgjFFv
#define isSameUrl kOrgchLtZlZwFecX
#define MatrixConcatenation wwpyEJaQaIAiJWBB
#define MatrixOrDouble jEvlHqVQlBRsbBRS
#define horizontalConcatenate RtJFtVNrFWWkMJev
#define resData btpfYaKQlSgcZETu
#define verticalConcatenate XVWUyOWhcLBxViGj
#define Matrix tDSAbgIfhDibdwhN
#define AAPoint gwVgoMWZIaOlZhlX
#define translation sFKkSUfORQJmjXyv
#define MatrixMultiplication LONegParWKiuIOXk
#define AASphereView CGIELaxjKeMKkzeZ
#define MatrixCreation mgKIWovvFSVWiwEB
#define MatrixSubscripting gaEZxQfeJYBZraQJ
#define sphereContentView YTqJiiJbfqFmnXyN
#define sphereView pjNcPfLbWtABxrgR
#define resetSphereView eMexGLqJfpMWXZQk
#define showSphere FpRHFOAdDUMMyAse
#define tags pAjBJfYJsvMVctic
#define displaySize ifcikOZUUtDUVqyl
#define button wlBxVdeaylaigSOd
#define overWebVC dxAJJvJqBmFxZXqO
#define accObj OXpMphozjKyqTbfd
#define CurrencyObject eLvEGktImYmURlBP
#define id cxtwOicBnFjWKSfB
#define currencyName CsVROjsWgjseVcOf
#define currencySymbol PCLeSsKVwLrmHjYi
#define CurrencyTools ulTTjhLuIjRPnlJX
#define freeCurrencyApiUrl hIafThNGyJzpjSvK
#define freeCurrencyAppKey HDitBsnPEvLZffLN
#define CurrencyName HGtKmhcSoiBMooCu
#define en plMTkXuBBWwYDfje
#define cn KFxqsSJtRKLAHgym
#define getCurrencyNameCn udytmieRfDkVOknp
#define getCurrencyObjectArray dpmDwtHmWiunsxqJ
#define currencyArray dEoCasUnaDUmaXLF
#define currencyDic TaFeFJGvdpzTHhzr
#define currencyKey krxdyVGTVgyhKJEu
#define currencyName VhBKhhxNjQJAWPOJ
#define currencySymbol mzXELqCKLjHivexq
#define currencyObj fNZRvUGAbeKYkPAj
#define currencyMainView jTKorZQZasRCdXVt
#define currencyTitleLabel bmOfjKjMsqUzMlGh
#define currencyFromView MMzeTIkyIaRIFyyr
#define currencyDescLabel1 YfvgaOkqXXrFwltO
#define currencyToView LcWJiAiRYHZmHMGu
#define currencyDescLabel2 SSiiAWHfXhqoKBOR
#define currencyInputTextField ftgejxsYGUvqjrAp
#define currencyStartBtn JRorBrzkkVXiqBpr
#define currencyResultTitleView gSBPTpNkmeUOmCif
#define currencyResultTitleLabel gtyVLPhOkKtPGlhC
#define currencyResultLabelMain EqcrZeUzZCuOGbmW
#define currencyResultLabelSub kpIbDdQinDGqsnXP
#define currencyFromSpinner CeRJpToSzLkflJmy
#define currencyToSpinner kOnJBwbhCUfpJzfI
#define currencyObjectArray usJvMuupMkyEocxy
#define currencyNameArray iBAhqqdqnkQJJPGE
#define currencyFromNameArray nDtGGTQvjJXrVfBW
#define currencyToNameArray PXQwcsJHdyBIpten
#define isSpinnerInit bolDkNurMxveBbXm
#define currencyObjArray DSaHkKqkSwhFnshr
#define valueText ASBsFXklKydpRqMa
#define valueDouble orHuQyLCFveuYNjx
#define fromObjIndex XpGAyqXoxsnlVgeZ
#define toObjIndex xuPXcBkYYrPiaQDI
#define fromConName dVbdkFfIGcFRosMo
#define toConName MkKQYwaHGbUydQFA
#define currencyPer sqWnQyCeEQhmVZOk
#define per zdkhTJzGiVumEveY
#define formatter oMvvxuoiDGWlEbDf
#define valueString NwOaeGxDCcePVOMY
#endif
